<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
    </PropertyGroup>

    <ItemGroup>
        <Compile Include="TestUtils.fs" />
        <Compile Include="TestPpmOutput.fs" />
        <Compile Include="TestRay.fs" />
        <Compile Include="TestSphereIntersection.fs" />
        <EmbeddedResource Include="PpmOutputExample.txt" />
        <Compile Include="TestPixel.fs" />
        <Compile Include="TestPlane.fs" />
        <Compile Include="TestSphere.fs" />
        <Compile Include="TestRandom.fs" />
        <Compile Include="TestBoundingBox.fs" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FsCheck" Version="3.0.0-rc3" />
      <PackageReference Include="FsUnit" Version="7.0.0" />
      <PackageReference Include="NUnit" Version="4.3.1" />
      <PackageReference Include="NUnit3TestAdapter" Version="4.6.0" />
      <PackageReference Include="System.IO.Abstractions.TestingHelpers" Version="21.1.7" />
      <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.12.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\RayTracing\RayTracing.fsproj" />
    </ItemGroup>

</Project>
